### ISSUE TITLE
round的含义

### ISSUE THREAD

**Issue by castoner** [yjsx/PFilter#4]
您好，有两个问题不是很清楚，请教一下。
1、请问这里的round还有r是指时间？还有其他具体含义吗？
` double round = (map_in->points[pointSearchInd[0]].r +
                               map_in->points[pointSearchInd[1]].r +
                               map_in->points[pointSearchInd[2]].r +
                               map_in->points[pointSearchInd[3]].r +
                               map_in->points[pointSearchInd[4]].r) /
                              5.0;`

2、还有一个问题是`if (observe / round > 5)
                    observe = 255;`
这里的除法是什么含义呢？
谢谢解答~

**Comment by yjsx** [comment]
您好，
（1）这里的round指地图点被建立距当前帧的时间，与论文中的k-k_0 含义相同；另外为了实现方便以及可视化清晰，我使用XYZRGB的点云格式，并把round赋给了r，observe赋给了g，这样就可以显示出论文中红色和绿色的效果。
（2）这个是为了优化效果的小设置，因为每一个特征点会在地图中寻找5个最近点，所以我把平均可以被五个特征点以上detect的地图点永久保留在地图中。这一行没什么太大的作用，我后续会删掉之后测试一下效果。

**Comment by castoner** [comment]
明白了，谢谢大佬
